---
name: cmake-quality
description: 'Build and test using cmake, focused on simple, source code first libraries and components'
branding:
  icon: 'compass'
  color: 'orange'
inputs:
  output_directory:
    description: 'CMake build directory'
    default: 'out'
  source_directory:
    description: 'CMake source directory'
    default: ''
  dependencies:
    description: 'Extra dependencies as apt packages to install'
    default: ''
  cmake_configure_commands:
    description: 'CMake configure commands (appended to default one)'
    default: ''
  cmake_build_targets:
    description: 'CMake configure commands (appended to default one, use none to skip building)'
    default: 'all'
  ctest_enable:
    description: 'Enable running ctest in build directory after build'
    default: false
  ctest_flags:
    description: 'CTest extra flags to pass'
    default: ''
  ctest_coverage:
    description: 'CTest colected coverage data upload'
    default: ''
  cmake_install:
    description: 'Enable running install in build directory after build'
    default: false
runs:
  using: 'docker'
  image: 'docker.pkg.github.com/rainlabs-eu/cmake-quality-action/environment:latest'
